### ISSUE TITLE
Test all FSRs on Arduino Uno

### ISSUE THREAD

**Issue by indirectjump** [grvashu/reride2#65]

**Comment by indirectjump** [comment]
To be done by Apoorva/Simran, Ruchita/Puneeth to shadow.

**Comment by ruchitampania** [comment]
[ReRide (Weight Sensor Testing) - Sheet1.pdf](https://github.com/grvashu/reride2/files/2802551/ReRide.Weight.Sensor.Testing.-.Sheet1.pdf)
